### ISSUE TITLE
[Suggestion] Button support for More Overlays

### ISSUE THREAD

**Issue by rigerc** [UniversalLP/JustEnoughButtons#10]
Buttons for the More Overlays mod would be neat! https://minecraft.curseforge.com/projects/more-overlays

Don't know if it's possible because they use a keyboard shortcut and not a command.

**Comment by univrsal** [comment]
Support in what way?
JustEnoughButtons already adds a light overlay and a shortcut to F3 + G (Showing chunk borders) when More Overlays isn't installed.

**Comment by rigerc** [comment]
OH didn't know that! Disregard
