### ISSUE TITLE
Save/Load buttons register clicks even when overlapped by other GUIs

### ISSUE THREAD

**Issue by thetaCriterion** [UniversalLP/JustEnoughButtons#11]
![e0c841ce-90e1-11e6-9c18-1f2e07d684ba](https://cloud.githubusercontent.com/assets/22810439/19346696/9c18b67c-90f9-11e6-9ffb-ccadd42e2b6d.png)

Note how the Save button underneath the interface is highlighted. Clicking activates the button and not the item drawn above it.

**Comment by univrsal** [comment]
So I looked into this, and sadly I don't think there's a way to see how much width the gui takes up, so I think the only way is to hide the save buttons.
I added a hotkey to hide the buttons, which should make that easier.
