### ISSUE TITLE
new crash with forge and justenough buttons

### ISSUE THREAD

**Issue by kzintiwife** [UniversalLP/JustEnoughButtons#13]
1. When i open the inventory and move the mouse, the game says shutting down internal server. (this is repeatable), 
troubleshooting done:
a. i reloaded forge and this mod. 
b. I only installed this mod. 
c. i created a new world as well.  
crashed once i opened the inventory again. 
d. i loaded just forge and the game was fine when i went into the inventory. 

Not really sure what happened or why this just started for me.  if i am reading the crash report wrong, sorry its my first one to actually look at

2. i have forge 1.11-forge1.11-13.19.1.2189  (it is the latest recommended - 12/9/16 10:46:00pm), also running windows 10 and the latest 64bit java

[crash-2016-12-15_03.03.29-client.txt](https://github.com/UniversalLP/JustEnoughButtons/files/654368/crash-2016-12-15_03.03.29-client.txt)

**Comment by kzintiwife** [comment]
well i went and reinstalled minecraft from the ground up and its working just fine now..

**Comment by univrsal** [comment]
So this seems like jlwg had issues with the keyboard.
I changed the handling of keybinds a little, but since this seems to have resolved already I'll leave it at that.
