### ISSUE TITLE
Modlist?

### ISSUE THREAD

**Issue by knubbis93** [UniversalLP/JustEnoughButtons#16]
could i ask if you could add kinda like not enough items mod list so i could see what mods there are on servers? it would help me out alot and is it difficult to do? i want to stay with jei and Not enough buttons and not use Nei i like your mods and addons but im really missing the modslist tab kind regards knubbis93

**Comment by univrsal** [comment]
Do you mean this list?
![NEI Subsets](http://i.imgur.com/ilZpsn1.png)
If so I'll see what I can do

**Comment by knubbis93** [comment]
Yes exactly that list i miss it so much that would be amazing if you could add :D

**Comment by univrsal** [comment]
So this is what I came up with:

![2017-01-20_19 36 39](https://cloud.githubusercontent.com/assets/8353672/22160858/d849e03e-df47-11e6-8b4f-bf1ad7278cf2.png)
It lists all mods that add items, and when clicking on one it'll tell JEI to list the items of that mod.
You can scroll through the list if there're more mods than it can fit on the screen

**Comment by knubbis93** [comment]
amazing thanks so much <3 briliant
