### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by jules552** [UniversalLP/JustEnoughButtons#2]
I have the french and french Canadian Translation if you would, but there is a little bug, the "Switch to" is not translate, can you fix that?

[fr_CA.txt](https://github.com/UniversalLP/JustEnoughButtons/files/417983/fr_CA.txt)

[fr_FR.txt](https://github.com/UniversalLP/JustEnoughButtons/files/417984/fr_FR.txt)

You have just to rename this file with a .lang and you can use it ^^

Thank you for your work ^^

**Comment by univrsal** [comment]
Fixed it :D
![2016-08-15_14 25 12](https://cloud.githubusercontent.com/assets/8353672/17664527/068fe7b0-62f5-11e6-9e69-b0c1eaed7c83.png)

The translation will be available in the next release, thanks for translating!
