### ISSUE TITLE
[Suggestion] Survival Mode

### ISSUE THREAD

**Issue by InterPlay02** [UniversalLP/JustEnoughButtons#26]
This mod is awesome, but I really think that _these buttons should not be visible in survival mode._ Otherwise I will be able to change my gamemode at any time. But, if I started a map in survival mode, this means I do NOT want to use cheatmode to get the items.
**1 ~** Only if I change the gamemode (by typing: /gamemode 1 or 0),
**2 ~** OR if I start a map in creative mode I should be able to see these buttons.

Beside this, the mod is very useful.

**Comment by univrsal** [comment]
I'm not quite sure how you want me to put that into a feature.
The buttons can be hidden by pressing Ctrl+H and you can disable them over the config.
If I'd disable them when in survival someone who's testing in survival couldn't use them.

Wouldn't it just work for you to hide them with the keybind?

**Comment by univrsal** [comment]
Since I didn't get a response I'll just have this closed. If you still want this implemented you'll have to give me a little more detail on what you exactly want
