### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by BakermanLP** [UniversalLP/JustEnoughButtons#29]
Hello,

I got a crash on startup of the client with the new version *justenoughbuttons-1.10.2-1.8.jar***. If I revert to justenoughbuttons-1.10.2-1.7.3.jar everything works well

Here is the crash log file:
https://pastebin.com/i8uVrLsG

Is the error on my side? 

Thanks for reading

Michael (aka BakermanLP)

**Comment by univrsal** [comment]
Might be that I used an outdated version of the ~~JEI~~ Forge API. I'll update it and see if that fixes it

**Comment by calloatti** [comment]
Having  exactly the same problem, same solution.

**Comment by univrsal** [comment]
Well this seems like a really annoying isssue. It works in my dev environment but doesn't when I compile it...
But I think I fixed it by not using the getkeys() method. I'll release it later

Edit: It's up as 1.10.2-1.8.1
If you still have any issues leave a comment
