### ISSUE TITLE
Permission Issues and Kicked from server on kill all entities

### ISSUE THREAD

**Issue by Konclan** [UniversalLP/JustEnoughButtons#30]
Magnet and trash currently works without operator, even with the require operator true.
The kill all entities button kicks you from the server (with operator but that I assume it just doesn't work without unless configed otherwise).

**Comment by univrsal** [comment]
I've fixed the permission issues and I'll see what I can do about the kill entities button. I'll see what the issue is with the kill entities button

**Comment by univrsal** [comment]
Alright I fixed the kill entities button and also fixed issues with it in the nether.
I'll make a release of it soon
