### ISSUE TITLE
Crash when saving inventory to a slot(justenoughbuttons-1.10.2-1.8.1)

### ISSUE THREAD

**Issue by BuckTheWeasel** [UniversalLP/JustEnoughButtons#31]
I was Trying to save some slops from ArchitectureCraft and some scarfford from immersive engineering,
error Log here : https://pastebin.com/qassAPPf

Happens Both with server and Client

**Comment by univrsal** [comment]
I'll look into it, but it'll have to wait until at least tomorrow.

**Comment by univrsal** [comment]
Alright this was a minor mistake that happened when backporting from 1.11, whoops.
It'll be fixed in the next version
