### ISSUE TITLE
Dynamic Surroundings Keybindings Compatibility

### ISSUE THREAD

**Issue by Jerzerak** [UniversalLP/JustEnoughButtons#32]
[Dynamic Surroundings](https://minecraft.curseforge.com/projects/dynamic-surroundings) currently adds light level & chunk border overlay's...would it be possible to add support similar to the More Overlay's compatibility so the JEB keybindings aren't registered if Dynamic Surroundings is installed?

**Comment by univrsal** [comment]
Yeah I'm on it

EDIT: I've implemented it into the 1.10.2 version and the 1.11.2 version will follow shortly.
I also added a config to disable the keybinds, if any other mods come along with the same keybinds.
There'll be a release on curseforge later

**Comment by Jerzerak** [comment]
You rock man! Thanks for the quick response and release!
