### ISSUE TITLE
[1.12] Console output spam

### ISSUE THREAD

**Issue by pWn3d1337** [UniversalLP/JustEnoughButtons#35]
> [10:48:52] [main/INFO]: [STDOUT]: TOP 112

When inventory is opened I get spammed with messages like that in sysout.

version: 1.12-1.1

**Comment by JasonKillsUs** [comment]
same here:
"[main/INFO] [STDOUT/]: [de.universallp.justenoughbuttons.client.ClientProxy:getGuiTop:110]: TOP 29"

thanks

**Comment by univrsal** [comment]
Ugh, I left that in there? Fixed in 1.12-1.2
