### ISSUE TITLE
[1.12] [1.2] Move the UI?

### ISSUE THREAD

**Issue by Kris1432** [UniversalLP/JustEnoughButtons#36]
Is there anyway to either move or remove the UI for JustEnoughButtons as its overlapping FTB Utils. 

Or anything that can be done to work with this? 

![2017-07-10_22 13 17](https://user-images.githubusercontent.com/3301022/28040229-10045bde-65bd-11e7-8bc6-f2f3ad110f26.png)

**Comment by univrsal** [comment]
Mod options > Just Enough Buttons > position
xOffset & yOffset can move all buttons (except the Mods button):

![config](http://hnng.moe/f/SVH)
![config](http://hnng.moe/f/SVI)
