### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Syndaryl** [UniversalLP/JustEnoughButtons#39]
JEB is spewing out the following debug message once a tick; I've had to remove it to prevent my logs from taking over everything.

[18:04:38] [main/INFO] [STDOUT]: [de.universallp.justenoughbuttons.client.ClientProxy:getGuiTop:110]: TOP 58

The "58" changes periodically.

**Comment by univrsal** [comment]
Ugh, I've made that mistake so many times it's slowly getting embarrassing...
I'll fix it as soon as possible

**Comment by Syndaryl** [comment]
It's worth wrapping the log output in a "debug print" method and use a
debugging config setting.

**Comment by univrsal** [comment]
Should be fixed in the next build.

**Comment by Syndaryl** [comment]
Ta much
