### ISSUE TITLE
[Enhancement] Cycle between modes

### ISSUE THREAD

**Issue by rigerc** [UniversalLP/JustEnoughButtons#4]
Hi, really like your mod! Helps out a lot. Only gripe I have is that the change mode button isn't a toggle. It defaults to 'set to creative' even if you're already in creative, so to get to survival I have to press it 2-3 times.

Keep up the great work!

**Comment by univrsal** [comment]
Thanks, I'll look into that

**Comment by univrsal** [comment]
Ok, I changed it. So now if the button is on creative and you for example switch to creative using the chat, the button will cycle to the next gamemode.
Also if you join a world and you're already in creative it'll also cycle to the next gamemode.

Let me know if find any more issues with that
