### ISSUE TITLE
1.2.2-5 claims that it is 1.12.0-compatible in Twitch Launcher

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [UniversalLP/JustEnoughButtons#40]

**Comment by univrsal** [comment]
I usually just assume that a mod is compatible between minor releases, but I guess that wasn't the case this time.
I'll see if it runs when I change the minimum version

**Comment by Pythonic-Rainbow** [comment]
No one uses 1.2.2 anymore, 1.5 years passed. Time flies!
