### ISSUE TITLE
No permissions while on server?

### ISSUE THREAD

**Issue by LemADEC** [UniversalLP/JustEnoughButtons#45]
As of justenoughbuttons-1.12.2-1.2.2-5 with spongeforge-1.12.2-2705-7.1.0-BETA-3383, the buttons fail saying
```
[18:45:54] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] You do not have permission to use this command
```

On the server, no command is logged, no permission is checked.
I'm effectively OP on the server.
The mod is installed on both client and server.

Any thoughts on what could be causing this?

**Comment by univrsal** [comment]
I'm not sure, the mod just goes through the list of Operators and if the current player is included it'll execute the command.
Otherwise the message gets printed in chat. I never used sponge, but it has posed some problems in the past. I don't really have time right now to setup sponge to test this, though

**Comment by LemADEC** [comment]
LuckPerms, our permission plugin, replaces the OP list, so there might some interference there.
Since Sponge already check permissions for commands, could the buttons just send the commands independently of an OP list?

**Comment by univrsal** [comment]
The thing is, that when JEB is installed on the server, it won't use chat commands, instead the server will directly do whatever task was requested by the player.
If you want it to send chat commands, you don't have to install JEB on the server

**Comment by LemADEC** [comment]
Ok, that did the trick. Only magnet is incompatible, but that's not needed for us. Thanks!

**Comment by univrsal** [comment]
Glad this works for you, even though I don't like leaving the problem at that, but I'm not really working on Minecraft mods right now.
