### ISSUE TITLE
Weird crash shortly after loading a world

### ISSUE THREAD

**Issue by SissyTrashQueen** [UniversalLP/JustEnoughButtons#53]
I load up my world, once inside I simply try to change the gamemode to creative through the mod's button and it crashes.
The world wasn't fully rendered around me but I didn't wait for it to load, probably the crash is because of this.

Crash report: https://hastebin.com/ewehovituf.rb

**Comment by univrsal** [comment]
yeah the mod subset button seems to be broken. I haven't gotten around to fixing it yet since gradle is giving me problems, I'll try to take a look at it though
