### ISSUE TITLE
Using Just Enough Buttons in my Modpack

### ISSUE THREAD

**Issue by Leppan** [UniversalLP/JustEnoughButtons#56]
Hi! I am an ordinary modpack creator. I would like to upload them publicly. Can I use your Just Enough Buttons mod for my modpack? Thanks for the answer

**Comment by univrsal** [comment]
You can, although I'm not sure why you'd want to use such an ancient mod.

**Comment by Leppan** [comment]
> You can, although I'm not sure why you'd want to use such an ancient mod.

Thank you very much
