### ISSUE TITLE
[Suggestion] Inventory sets like old NEI

### ISSUE THREAD

**Issue by rigerc** [UniversalLP/JustEnoughButtons#6]
Would love to see the feature of inventory sets like NEI had. The ability to take a snapshot of your inventory and store it is very handy for debugging and creative players.

Great mod by the way, love the custom command buttons!

**Comment by univrsal** [comment]
Thanks for the suggestion!
I'll see if I can implement that. But for items with a lot of NBT data, this would require the mod to be installed on the server aswell, since the /give command has a maximum length, which would be exceeded by all the nbt tags.
But I'll see what I can do

**Comment by univrsal** [comment]
Aaand it's implemented. Hope it works as expected
